config/routes.rb
Gemgem::Application.routes.draw do
  root 'home#index'

  resources :sessions do
    collection do
      get :signout
    end
  end

  resources :things do
    resources :ratings
    member do
      patch :crop
    end
  end
  post 'things/:id/form' => 'things#form', as: :rating_form

  resources :ratings do
    member do
      post :undo
    end
  end

  resources :users do
    collection do
      get :search
    end

    member do
      get :confirm
      patch :confirm_save
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Monban::ControllerHelpers
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ratings = Rating::Twin.finders.all
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new # DISCUSS: we don't need this anymore.
    # thing   =
    rating  = Rating::Twin.new
    @form   = Rating::Form.new(rating)
  end

  # DISCUSS: controller may only work with @form, not with @entity.
  def create
    params[:rating][:thing] = {:id => params[:thing_id]} # it is possible to set stuff before triggering Create.

    Trailblazer::Endpoint::Create.new.call(self, params,
      {form: {
        success: lambda { |form| redirect_to thing_path(form.model.thing.id) },
        invalid: lambda { |form| puts form.errors.messages.inspect; render action: "new" } # if this did actually call #new as in cells, we don't need the form object.
      }},
      Rating)
  end

  def edit
    rating  = Rating::Twin.find(params[:id])
    @form   = Rating::Form.new(rating)

    render :action => :new
  end

  def update
    rating  = Rating::Twin.find(params[:id])

    raise rating.rateable.inspect
    # rating.rateable = Object.new


    @form   = Rating::Form.new(rating)

    if @form.validate(params[:rating])
      @form.save
      @form.model.save

      return redirect_to edit_rateable_rating_path(1, rating) # rating.url.edit
    end

    render :action => :new
  end

  def show
    @rating = Rating::Twin.find(params[:id])
  end

  def destroy
    rating = Rating::Delete[id: params[:id]]
    redirect_to thing_path(rating.thing.id)
  end

   def undo
    Rating::Undo.run(id: params[:id]) do |rating|
      redirect_to thing_path(rating.thing.id)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @form = Session::Signin.present({})
  end

  # TODO: test me.
  def create
    @form = Session::Signin.run(params[:session]) do |op|
      sign_in(op)
      return redirect_to things_path
    end.contract

    render action: :new
  end

  # TODO: test me.
  def signout
    Session::Signout.run({}) do
      sign_out
      redirect_to things_path
    end
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  respond_to :html, :json
  include Trailblazer::Operation::Controller

  def index
    # pagination?
    # collection [..]
    @things = Thing.all.order("'created_at' DESC")
  end

  def new
    present Thing::Create
  end

  def create
    run Thing::Create do |op|
      redirect_to op.model
    end.else do |op|
      render action: :new
    end
  end

  def edit
    @form = Thing::Update.contract(params)
    @crop = Thing::Crop.contract(params)

    render action: :new
  end

  def update
    @form = Thing::Update.run(params[:thing]) do |form|
        return redirect_to thing_path(form.model.id)
      end

      return render action: "new"
  end

  # has_cell :

  # TODO: test with and without image
  def show
    present Thing::Show do
      @form = Rating::New.present(params)
      @thing = @model
    end
  end

  def form # TODO: this should happen in the cell-ajax.
    # DISCUSS: we could also think about hooking an Endpoint/Operation to a route that then renders the cell?
    # but, why? UI and API have different behaviour anyway.
    op = Rating::Create.run(params) do |op|
      flash[:notice] = op.unconfirmed? ? "Check your email and confirm your account!" : "All good."
      return redirect_to thing_path(op.model.thing)
    end

    # this should be op.thing
    @thing = op.contract.thing # HTML logic.
    @form = op.contract

    render action: :show
  end

  def crop
    redirect_to thing_path(Thing::Crop[params[:thing]])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json#, :html
  include Trailblazer::Operation::Controller

  def search
    respond_with User::Operation::Search[params]
    # render json: [{"label"=>"mylabel","value"=>"myvalue"}]
  end

  def show
    present User::Show
  end



  def edit
    # TODO: authorization, is that me trying to update?

    present User::Update do |op| # this runs op."contract" but returns the op. Op#init ?
      # this is absolutely ok here - this is presentation logic only for HTML.
      # i could also use User::Edit but i don't need it presently.
      # @form = op.contract
    end
  end

  def update
    # ideally,we only need html config here. if not, pass format into block?!
    # json etc should be handled in responder per default (api behaviour).
    run User::Update do |op|
      # html only.
      flash[:notice] = "Updated."
      render action: :edit # DISCUSS: should that be done automatically IN #run?
    end.else do
      render action: :edit # invalid.
    end
  end

  # maybe that should be abstracted in a higher Operation?
  before_filter :is_confirm_allowed?, only: :confirm
  def confirm
    @form = User::Operation::Confirm.contract(params)
  end

  # TODO: pass on confirmation_token for locking out idiots.
  def confirm_save
    op=User::Operation::Confirm.run(params) do |op|
      # this is controller-specific. i don't want that in operation (imagine that on the console).
      sign_in(op.contract.model) # from Monban::ControllerHelpers.
      flash[:notice] = "Yay, you're signed in, buddy!"
      return redirect_to things_path
    end

    @form = op.contract
    render action: :confirm # DISCUSS: rendering should work on Op?
  end

private
  def is_confirm_allowed?
    # TODO: raise 401 Unauthorized / show decent "want another token?" page.
    raise unless Monban::IsConfirmationAllowed[params]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/views/home/index.haml
%h1 Gemgem!!!

%h3 Latest

%ul
- @ratings.each do |rating|
  %li
    = concept("rating/cell", rating).call

app/views/layouts/_messages.haml
- flashes = {:notice => 'success', :alert => 'standard', :error => 'alert', :secondary => 'secondary'}
- flashes.each do |key, value|
  - if flash[key]
    .alert-box{:class => value, :data => { :alert => '' } }
      = flash[key]
      =# link_to '&times;'.html_safe, '#', :class => 'close'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title gemgem - Feedback for a better world.
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tag
  %body
    .row

      .small-4.column
        = yield
      .small-3.column
        - # TODO: test me.
        - if signed_in?
          Hi, #{current_user.email}
          = link_to "Sign out", signout_sessions_path
        - else
          = link_to "Sign in", new_session_path


        = render 'layouts/messages'

        %ul
          %li
            = link_to "New Thing", new_thing_path
          %li
            = link_to "Things...", things_path

app/views/ratings/create.haml
That was awesome!

= @form.model.inspect

app/views/ratings/new.html.haml
%h1 Rating#new
%p Find me in app/views/rating/new.html.haml

-# form_for calls rateable_entity_rating_path now, which is stupid.
= simple_form_for [Thing::Twin.new, @form], url: thing_ratings_path(thing_id: 1) do |f|
  = f.input :comment
  = f.button :submit
  -# DISCUSS: we do *not* embed the rateable_id here.


= @form.errors.messages

app/views/ratings/show.haml
%h1 #{@rating.id}

= @rating.comment

app/views/things/index.html.haml
%h1 Things#index

%ul
  = concept("thing/cell/row", collection: @things)

app/views/things/new.html.haml
%h2 What do you want to talk about?

= simple_form_for [@form] do |f|
  = f.input :name, placeholder: "Name", label: false, :as => :string
  = f.input :image, as: :file
  - # this should appear in edit mode, only.
  - if @form.model.image.exists?
    = image_tag @form.model.image[:thumb].url


  -# TODO: the id should be around in edit mode only.
  = f.hidden_field :id, value: @form.model.id

  %fieldset
    %legend Do you know any authors?
    = f.fields_for :authors do |a|
      = a.input :email
      = a.hidden_field :id

  = f.button :submit, class: :expand

:javascript
  $("input.email").autocomplete({
    source: '#{search_users_path}',
    select: function(event, ui) {
      id_input = $(':input:eq(' + ($(':input').index(this) + 1) + ')');
      id_input.val(ui.item.value)
      // $(this).val(ui.item.label)
    }
  });

= @form.errors.messages


- if @crop
  - if @form.model.image.exists?
    = image_tag @form.model.image[:original].url, width: 300, id: :croppable # "croppable"
  = form_for @crop, url: crop_thing_path(@crop.model) do |f|
    = f.text_field :x, :id => 'crop_x'
    = f.text_field :y, :id => 'crop_y'
    = f.text_field :w, :id => 'crop_w'
    = f.text_field :h, :id => 'crop_h'
    = f.text_field :id, value: @crop.model.id
    = f.submit "Crop!"

  :javascript
    $(function(){

      $('#croppable').Jcrop({
        onChange: updateForm,
        aspectRatio: 1
      });

    });

    function updateForm(coords)
    {
      $('#crop_x').val(coords.x);
      $('#crop_y').val(coords.y);
      $('#crop_w').val(coords.w);
      $('#crop_h').val(coords.h);

      var rx = 100 / coords.w;
      var ry = 100 / coords.h;

      $('#preview').css({
        width: Math.round(rx * 500) + 'px',
        height: Math.round(ry * 370) + 'px',
        marginLeft: '-' + Math.round(rx * coords.x) + 'px',
        marginTop: '-' + Math.round(ry * coords.y) + 'px'
      });
    }

app/views/things/show.haml
%h1 #{@thing.name}
= image_tag @thing.image[:thumb].url if @thing.image.exists?

= concept("rating/cell/form", @form).call

%ul
  - @thing.ratings.reverse.each do |rating|
    %li
      = rating.id
      = link_to rating.comment, thing_rating_path(@thing.id, rating.id)
      #{rating.weight}
      - if rating.deleted?
        = link_to "Undo", undo_rating_path(rating.id), method: :post
      - else
        = link_to "Delete", rating_path(rating.id), method: :delete
      - # TODO: the URL helpers are so clumsy, make de-nesting resources easier.

      = rating.user.email if rating.user

app/views/things/show.html.haml
.header
  = image_tag @thing.image[:thumb].url if @thing.image.exists?

  %h1
    #{@thing.name}
    = link_to "Edit", edit_thing_path(@thing)

  By
  - @thing.authors.each do |author|
    = author.email

-# c/u should be passed via a Twin that is set up in the top Op/Comp.
= concept("rating/cell/form", @form, current_user: current_user).call

%ul
  - @thing.ratings.reverse.each do |rating|
    %li
      = concept("rating/cell/row", rating).call

app/views/users/confirm.haml
%h1 #{@form.model.email}, confirm your account!

= simple_form_for(@form, url: confirm_save_user_path(@form.model)) do |f|
  = f.input :password, placeholder: "Password", label: false
  = f.input :password_confirmation, placeholder: "Password, again", label: false

  = f.button :submit, "Confirm!", class: :expand

%h3 What you said...

-# TODO: op.ratings..., access via Op.
-# TODO: display with thing!
= concept("rating/cell/row", @form.model.ratings.first).call if @form.model.ratings.first

app/views/users/edit.haml
%h2 Edit Your Profile

= simple_form_for [@form] do |f|
  = f.input :name, placeholder: "Name", label: false, :as => :string
  = f.input :email, placeholder: "Email", label: false, :as => :string
  = f.input :image, as: :file
  - # this should appear in edit mode, only.
  - if @model.image.exists?
    = image_tag @model.image[:thumb].url

  = f.button :submit, class: :expand

  = @form.errors.to_s

app/views/users/show.haml
%h1 #{@model.email}

%ul
  - @model.ratings.each do |rating|
    %li #{rating.inspect}

app/views/users/show.html.haml
%h1 #{@model.email}

%ul
  - @model.ratings.each do |rating|
    %li #{rating.inspect}